# -*- mode: ruby -*-
# vi: set ft=ruby:

nodes = [
	{:hostname => "main", :ip => "192.168.5.10", :cpus => 2, :mem => 2048},
	{:hostname => "worker", :ip => "192.168.5.11", :cpus => 2, :mem => 2048},
]

Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |vmachine|
			config.vm.box = "ubuntu/focal64"
			config.vm.box_check_update = false
			vmachine.vm.hostname = node[:hostname]
			vmachine.vm.network "private_network", ip: node[:ip]
			vmachine.vm.provider :virtualbox do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
			vmachine.vm.provision :shell, path: "k8s-common.sh"
		end
	end
end
