# -*- mode: ruby -*-
# vi: set ft=ruby:

nodes = [
	{:hostname => "main", :cpus => 2, :mem => 2048},
	{:hostname => "worker", :cpus => 2, :mem => 2048},
]

Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |vmachine|
			config.vm.box = "generic/ubuntu2010"
			config.vm.box_check_update = false
			vmachine.vm.hostname = node[:hostname]
			vmachine.vm.provider :libvirt do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
			vmachine.vm.provision :shell, path: "k8s-common.sh"
		end
	end
end
