# -*- mode: ruby -*-
# vi: set ft=ruby:

nodes = [
	{:hostname => "main", :cpus => 2, :mem => 3072},
]

Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |vmachine|
			vmachine.vm.box = "ubuntu/focal64"
			config.vm.box_check_update = false
			vmachine.vm.hostname = node[:hostname]
			vmachine.vm.provider :virtualbox do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
			vmachine.vm.provision :shell, path: "k8s-common.sh"
			vmachine.vm.provision :shell, path: "main.sh"
		end
	end
end
