name: project-ci
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: "Build runner image"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: |
          DOCKER_USER=mdnfiras
          RUNNER_IMG_TAG=$(echo -n $RUNNER_TOKEN | sha256sum - | cut -c1-15 )
          RES=$(curl -u mdnfiras:$DOCKER_TOKEN https://registry.hub.docker.com/v2/repositories/$DOCKER_USER/devopsies-runner/tags | { grep $RUNNER_IMG_TAG || true; } )
          if [ -z "$RES" ]; then
            echo "Did not find image with tag $RUNNER_IMG_TAG"
            docker login -u $DOCKER_USER -p $DOCKER_TOKEN
            cd runner
            curl -o actions-runner-linux-x64-2.283.2.tar.gz -L https://github.com/actions/runner/releases/download/v2.283.2/actions-runner-linux-x64-2.283.2.tar.gz
            echo "ef2b350068f7d581eb6840e3c399a42f9cb808f7ee9a0456f3ad97c84ccb2a9d  actions-runner-linux-x64-2.283.2.tar.gz" | shasum -a 256 -c
            mv actions-runner-linux-x64-2.283.2.tar.gz actions-runner-linux-x64.tar.gz
            docker build -t $DOCKER_USER/devopsies-runner:$RUNNER_IMG_TAG --build-arg RUNNER_TOKEN=$RUNNER_TOKEN --build-arg GITHUB_REPO=$REPO_URL .
            docker push $DOCKER_USER/devopsies-runner:$RUNNER_IMG_TAG
            docker tag $DOCKER_USER/devopsies-runner:$RUNNER_IMG_TAG $DOCKER_USER/devopsies-runner:latest
            docker push $DOCKER_USER/devopsies-runner:latest
            docker logout
          else
            echo "Found image with tag $RUNNER_IMG_TAG"
          fi